[package]
name = "fusb302b"
version = "0.1.0"
edition = "2024"
description = "A driver for the FUSB302B USB Type-C PD controller implementing usbpd-traits (uses device-driver crate)"
authors = ["Danila Gornushko <me@okhsunrog.dev>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/okhsunrog/fusb302b"
keywords = ["embedded-hal-driver", "async", "no-std", "usb-pd", "fusb302b"]
categories = ["embedded", "no-std", "no-std::no-alloc", "hardware-support"]
readme = "README.md"
documentation = "https://docs.rs/fusb302b"

[lib]
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors
test = false
bench = false

[dependencies]
embedded-hal-async = "1.0"
defmt = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }
# heapless = { version = "0.8", features = ["defmt-03"] }
embassy-time = "0.5"
usbpd-traits = "2.0.0"
device-driver = { version = "2.1.1", default-features = false, features = ["macros"] }
thiserror = { version = "2.0.12", default-features = false }

[features]
default = []
std = ["thiserror/std"]
log = ["dep:log"]
defmt = ["dep:defmt", "embedded-hal-async/defmt-03", "device-driver/defmt"]


